# Generated by Django 2.0.1 on 2021-06-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '组卷',
                'verbose_name_plural': '组卷',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finish', models.BooleanField(default=False, verbose_name='是否完成')),
                ('grade', models.FloatField(default=0, verbose_name='成绩')),
            ],
            options={
                'verbose_name': '学生考试',
                'verbose_name_plural': '学生考试',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_no', models.CharField(max_length=20, verbose_name='试卷编号')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='试卷')),
                ('time', models.DateTimeField(verbose_name='考试时间')),
                ('duration', models.CharField(choices=[('4', '60分钟'), ('2', '100分钟'), ('3', '90分钟'), ('1', '150分钟')], max_length=50, verbose_name='考试时长')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='题目')),
                ('option_a', models.CharField(max_length=100, verbose_name='A')),
                ('option_b', models.CharField(max_length=100, verbose_name='B')),
                ('option_c', models.CharField(max_length=100, verbose_name='C')),
                ('option_d', models.CharField(max_length=100, verbose_name='D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4, verbose_name='答案')),
                ('level', models.CharField(choices=[('1', '简单'), ('2', '一般'), ('3', '困难')], max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(default=1, verbose_name='分数')),
            ],
            options={
                'verbose_name': '试题管理',
                'verbose_name_plural': '试题管理',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='科目')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Subject', verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Subject', verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='paper',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='出题教师'),
        ),
        migrations.AddField(
            model_name='exam',
            name='paper_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='考试试卷'),
        ),
        migrations.AddField(
            model_name='exam',
            name='stu_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='考试学生'),
        ),
        migrations.AddField(
            model_name='createpaper',
            name='paper_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='所属试卷'),
        ),
        migrations.AddField(
            model_name='createpaper',
            name='question_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.QuestionBank', verbose_name='试题'),
        ),
    ]
