# Generated by Django 2.0.1 on 2021-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('dept', models.CharField(choices=[('信息工程学院', '信息工程学院'), ('电气与自动化学院', '电气与自动化学院'), ('外语外贸学院', '外语外贸学院'), ('理学院', '理学院'), ('建筑与测绘学院', '建筑与测绘学院'), ('机电学院', '机电学院'), ('经管学院', '经管学院'), ('马克思学院', '马克思学院')], default='信息工程学院', max_length=20, verbose_name='学院')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('cls', models.CharField(max_length=20, verbose_name='班级')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '学生管理',
                'verbose_name_plural': '学生管理',
            },
        ),
    ]
